from .order_tab import OrderTab
from .menu_tab import MenuTab
from .inventory_tab import InventoryTab
from .reports_tab import ReportsTab
from .dish_edit_dialog import DishEditDialog
from .inventory_edit_dialog import InventoryEditDialog
from .recipe_edit_dialog import RecipeEditDialog
from .dish_selection_dialog import DishSelectionDialog
from .login_dialog import LoginDialog